### ISSUE TITLE
Generelize how a struct is given a type and version

### ISSUE THREAD

**Issue by Momo10101** [symbol/catbuffer-parser#28]
Right now, the type and version of a struct is hardcoded in _EntityBody.type_ and _EntityBody.version_. This should preferably be generalized. Also instead of using const fields TRANSACTION_VERSION and TRANSACTION_TYPE, a field specific for this should be defined. An example could be, instead of this:

```yaml
  - comments: ''
    disposition: const
    name: TRANSACTION_VERSION
    signedness: unsigned
    size: 1
    type: byte
    value: 1
  - comments: ''
    disposition: const
    name: TRANSACTION_TYPE
    type: TransactionType
    value: AGGREGATE_COMPLETE
```

We could do something like this (just an example):

```yaml
  - type: struct_type TransactionType
    value: AGGREGATE_COMPLETE @1
    header: EntityBody         //<--- header where version and type of struct is stored
    version_field: version     //<--- the name of the field within the header defining the version
    type_field: type              //<--- the name of the field within the header defining  the type
```
It would be cleaner and would also make it easier to parse and at the same time more flexible where the type and version of a struct is stored.  The @ sign gives the version.
