### ISSUE TITLE
Consider supporting unions explicitly

### ISSUE THREAD

**Issue by Momo10101** [symbol/catbuffer-parser#30]
We should consider supporting unions directly. At the moment we do it indirectly with conditions when the same condition field is shared between multiple fields like so:

```yaml
  - comments: namespace duration
    condition: registration_type
    condition_operation: equals
    condition_value: ROOT
    name: duration
    type: BlockDuration

  - comments: parent namespace identifier
    condition: registration_type
    condition_operation: equals
    condition_value: CHILD
    name: parent_id
    type: NamespaceId
```
This is a bit messy. For example what happens if a user makes a mistake and for one variable puts the condition above to == ROOT and the other != CHILD. Then both fields would be read. Should the generator catch such errors? But perhaps that could a useful  behavior that a user wants? Should the generator be smart enough to know when to do a union and when to do conditions?

It would probably be cleaner to support unions directly by doing something like below and leaving conditions for conditions only:

```yaml
  - name: BlockNameUnion
    type: union
    switch: registration_type
    comments: ''
    layout:
    - name: duration
      type: BlockDuration
      case: ROOT
      comments: namespace duration

    - name: parent_id
      type: NamespaceId
      case: CHILD
      comments: parent namespace identifier
```

Ideally 'registration_type' should be defined before the union definition. Unfortunately that is not the case currently for symbol. We should think about how we want to deal with that, because right now to implement proper checks, it means that we have to do two passes of struct fields. If possible we should not allow registration_type to be defined after the union.
